# Generated by Django 4.1 on 2022-09-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220925_0025'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
            ],
        ),
    ]
